---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  BLOG_DB_NAME: blog
  BLOG_DB_USERNAME: userblog
  BLOG_DB_PASSWORD: passblog42@
  BLOG_DB_HOST: wp-db---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  BLOG_DB_NAME: blog
  BLOG_DB_USERNAME: userblog
  BLOG_DB_PASSWORD: passblog42@
  BLOG_DB_HOST: wp-db