apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-app
  name: wp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
        - image: wordpress
          name: wp-app
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: BLOG_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: BLOG_DB_USERNAME
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: BLOG_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: BLOG_DB_NAME